### DISCUSSION TITLE
My usecase for s3gw - cache for Gitlab CI

### DISCUSSION THREAD

**Discussion by sverkera** [s3gw-tech/s3gw#875] [General]
Hi,
I found this project when looking for a lightweight S3 gateway to use as cache for GitLab CI pipelines. As it looks like the community activities for the project hasn't picked up so I thought I'd describe my usecase which may be useful as inspiration for someone else. I see a need for this kind of simple S3 gateway for many purposes

I have gitlab runners in a k3s cluster which are managed by ArgoCD. I use the helm chart to deploy s3gw (to namespace gitlab-runner) like this
Chart.yaml:
```
apiVersion: v2
name: gitlab-runner-s3-cache
version: 0.23.1
dependencies:
  - name: s3gw
    version: 0.23.1
    repository: https://charts.s3gw.tech
```
values.yaml:
```
s3gw:
  ingress:
    enabled: false
  ui:
    enabled: false
  serviceName: "s3gw"
  privateDomain: "svc.cluster.local"
  accessKey: "s3gw"
  secretKey: "xxxxxxxx"
  storageSize: 1Gi
  storageClass:
    name: "longhorn"
  logLevel: "low"
```

Hence I can tell gitlab-runner to use s3gw.gitlab-runner.svc.cluster.local as address. I haven't found how to make gitlab-runner ignore self-signed certificate so I set Insecure=true to make it use http.

Since I only use S3 internally in this namespace I don't want to enable neither ingress nor ui, but that gave me a challenge that I had to create the bucket. I did that by execute a shell on the pod running s3gw and execute the below script to create runners-cache bucket:
```
zypper -n install --no-recommends awscli
export AWS_ACCESS_KEY_ID=s3gw
export AWS_SECRET_ACCESS_KEY=xxxxxx
export AWS_ENDPOINT_URL=http://s3gw.gitlab-runner.svc.cluster.local
aws s3 mb runners-cache
```

The issues I had was that I had to set storageClass.name even though leaving it empty should have selected the default storage class and that 100 Mbyte is reserved as minimum on the storage so when I to begin with set StorageSize: 100Mi then I got quota error whenever trying to put something in the bucket. Other than that it has worked like a charm.

An improvement would be to be able to set a list of buckets in values.yaml that should be created on deploy.
