### ISSUE TITLE
tools: lint is not linting

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#244]
```
Run DavidAnson/markdownlint-cli2-action@v7
markdownlint-cli2-config v0.5.1 (markdownlint v0.26.2)
Finding: '**/*.md'
Linting: 0 file(s)
Summary: 0 error(s)
```

this should be fixed by:

```
      - name: Lint
        uses: DavidAnson/markdownlint-cli2-action@v8
        with:
          command: config
          globs: |
            .github/workflows/config/custom.markdownlint.jsonc
            **/*.md
```
