### ISSUE TITLE
Question yaml options enhancement

### ISSUE THREAD

**Issue by abonillabeeche** [s3gw-tech/s3gw#341]
**Describe the bug** A clear and concise description of what the bug is.
This bug will include 4 change requests in the UI/questions.yaml for the Rancher chart.

1. Include the ability to point to a current TLS ingress secret, ie the Rancher ingress secret.
2. Clarify if cert-manager is needed or if its installed, we even ask for the namespace.
3. The Storage section is not clear that one needs to specify the name if a storageclass is not created. So it should be a dropdown of available Storageclasses. Since questions.yaml is used for Rancher, we should request a Longhorn instance or consume any available StorageClass, so a dropdown might just be the ideal way to go.
4. The s3 service name is separated from the S3 ingress section as opposed to the UI section that hint at which values should be there. The point is to make clear that the domain is the domain and the svc name is the actual endpoint URL short-name minus domain.

**Comment by votdev** [comment]
> So it should be a dropdown of available Storageclasses.

I'm currently not too familar with Rancher, but i suspect that this is not provided by the Rancher UI. You have to keep in mind that the install form is the visual representation of the Helm chart yaml. I don't think that Helm and Rancher support such interactive features. But maybe i'm totally wrong here.

**Comment by abonillabeeche** [comment]
All it needs is
` type: storageclass`
and it will show the available storageclasses. Perhaps it can be a subquestion if we don't want to install Longhorn. (which, I don't think we should...)

Something like

```
  # Storage
  - variable: storageSize
    description: "Storage Size"
    type: string
    default: 10Gi
    label: "Storage Size"
    group: "Storage"

  - variable: storageClass.create
    description: |
      Create a new opinionated storage class backed by and installing longhorn.io
    type: boolean
    default: true
    label: "Create Storage Class"
    group: "Storage"
    show_subquestion_if: false
    subquestions:
      - variable: storageClass.name
        description: "Storage Class Name"
        type: storageclass
        required: true
        label: "Storage Class"
        group: "Storage"
    show_subquestion_if: true
    subquestions:
      - variable: storageClass.name
        description: "Storage Class Name"
        type: string
        default: "longhorn-single"
        required: true
        label: "Storage Class"
        group: "Storage"
          ```
