### ISSUE TITLE
s3gw: update .github/workflows/release.yaml

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#445]
.github/workflows/release.yaml must be fixed to adequate the sources relocation in s3gw-ui repo.

```
      - name: Build and Push Container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            quay.io/s3gw/s3gw-ui:${{ github.ref_name }}
            quay.io/s3gw/s3gw-ui:latest
          file: ui/Dockerfile
          context: ui/src/frontend
```
to
```
      - name: Build and Push Container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            quay.io/s3gw/s3gw-ui:${{ github.ref_name }}
            quay.io/s3gw/s3gw-ui:latest
          file: ui/src/frontend/Dockerfile
          context: ui/src/frontend
```
