### ISSUE TITLE
Chart tries to issue wildcard certificate

### ISSUE THREAD

**Issue by amjadsaadeh** [s3gw-tech/s3gw#456]
**Describe the bug** 
When I install the s3gw helm chart on a fresh k3s cluster (traefik and cert-manager are already installed and work correctly), the certificate order for the API endpoint is pending forever. After investigation I just recognized, that the order for `s3gw-ingress-tls` tries to issue a wildcard certificate, but I don't have a ClusterIssuer for DNS challenge in place (and I cannot add one since my domain provider does not support an API for setting DNS records). The certificate issuing process for `s3gw-ui` service works just fine.

**To Reproduce** Steps to reproduce the behavior:

1. place `values.yml`:
```
# random valuea for default account username and password
accessKey:
secretKey:
serviceName: s3gw
publicDomain: "example.com"
privateDomain: "s3gw.svc.cluster.local"
ui:
  serviceName: s3gw-ui
  publicDomain: "example.com"
ingress:
  enabled: true
tlsIssuer: "s3gw-letsencrypt-issuer"
email: "admin@example.com"
```
2. run `helm install s3gw s3gw/s3gw --namespace s3gw --create-namespace -f s3gw.values.yml`

**Expected behavior** 

That I can access `s3gw.example.com` with an valid letsencrypt certificate.

**Additional context**

Frankly speaking I have no idea why an certificate for `*.s3gw.example.com` is necessary.
