### ISSUE TITLE
[BUG] Installation fails when using Let's Encrypt cluster issuer

### ISSUE THREAD

**Issue by PhanLe1010** [s3gw-tech/s3gw#671]
### **Describe the bug** A clear and concise description of what the bug is.

I am hitting 3 problems with TLS while deploying S3GW chart (v0.19.0) with Let's Encrypt cluster issuer:

### 1. The known issue 

https://github.com/aquarist-labs/s3gw/issues/655

### 2. AMCE wrong config

The second problem is the s3gw-letsencrpt cluster issuer has this special annotation ([link](https://github.com/aquarist-labs/s3gw-charts/blob/b953bc33315d3488024bdf455a8f341cbf496011/charts/s3gw/templates/tls-issuer.yaml#L40-L47)). 
```
    solvers:
    - http01:
        ingress:
          ingressTemplate:
            metadata:
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
```
When `cert-manager` tries to verify solving the ACME challenge, create an ingress resource to route the traffic from Let's Encrypt to a temporary ACME server pod. The ingress created will have these annotations. The problem is that these annotations instruct Traefik to expose the `https` port of the ACME server only (see more [link](https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/)). But the `cert-manager` is trying to contact the AMCE server on `http` port. This failed and the certificate was never issued.

### 3. Wildcard certificate cannot work with http01 solver

The s3gw ingress has this wildcard certificate (the one starts with *): [link](https://github.com/aquarist-labs/s3gw-charts/blob/b953bc33315d3488024bdf455a8f341cbf496011/charts/s3gw/templates/ingress-traefik.yaml#L18-L20). This mean that the Let's encrypt tls issuer must use dns01  resolver instead of the [current http01 resolver](https://github.com/aquarist-labs/s3gw-charts/blob/b953bc33315d3488024bdf455a8f341cbf496011/charts/s3gw/templates/tls-issuer.yaml#L41): ref https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates. Why do we need to have wildcard certificate?

### **To Reproduce** Steps to reproduce the behavior:

1. install s3gw v0.19.0 helm chart with:
    ```
    ---
    publicDomain: <your-public-domain>
    tlsIssuer: s3gw-letsencrypt-issuer
    email: <your-email>
    ui:
      enabled: true
      publicDomain: <your-public-domain>
    ingress:
      enabled: true
    storageClass:
      name: longhorn
      storageSize: 20Gi
    
    ```
1. s3gw deployment failed to start. See that certificates failed to be issued. Ingress resources are failing to get HTTPS.
