### ISSUE TITLE
The docker-compose.yaml file is incorrect

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#819]
With v0.23.0 there need to be done some changes in https://github.com/aquarist-labs/s3gw/blob/s3gw-v0.23/docker-compose.yaml

Rename RGW_SERVICE_URL -> S3GW_SERVICE_URL
Remove 
```
    command:
      - "--rgw-backend-store"
      - "sfs"
```
Finally it should look like:
```
---
version: "3.4"
services:
  s3gw:
    image: quay.io/s3gw/s3gw:v0.23.0-rc2
    restart: always
    ports:
      - "7480:7480"
    environment:
      S3GW_DEBUG: high
      RGW_DEFAULT_USER_ACCESS_KEY: "test"
      RGW_DEFAULT_USER_SECRET_KEY: "test"
    volumes:
      - data:/data

  s3gw-ui:
    image: quay.io/s3gw/s3gw-ui:v0.23.0-rc2
    restart: always
    stop_signal: SIGINT
    depends_on:
      - s3gw
    ports:
      - "8080:8080"
    environment:
      S3GW_SERVICE_URL: "http://localhost:3080"

  proxy:
    image: docker.io/nginx:latest
    restart: always
    depends_on:
      - s3gw-ui
    ports:
      - "80:80"
      - "3080:3080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  data:
```
