### ISSUE TITLE
The s3gw-ui container does not start

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#821]
When using the [(adapted) docker-compose.yaml](https://github.com/aquarist-labs/s3gw/issues/819)
```
---
version: "3.4"
services:
  s3gw:
    image: quay.io/s3gw/s3gw:v0.23.0-rc2
    restart: always
    ports:
      - "7480:7480"
    environment:
      S3GW_DEBUG: high
      RGW_DEFAULT_USER_ACCESS_KEY: "test"
      RGW_DEFAULT_USER_SECRET_KEY: "test"
    volumes:
      - data:/data

  s3gw-ui:
    image: quay.io/s3gw/s3gw-ui:v0.23.0-rc2
    restart: always
    stop_signal: SIGINT
    depends_on:
      - s3gw
    ports:
      - "8080:8080"
    environment:
      S3GW_SERVICE_URL: "http://localhost:3080"
      S3GW_UI_PATH: "/"

  proxy:
    image: docker.io/nginx:latest
    restart: always
    depends_on:
      - s3gw-ui
    ports:
      - "80:80"
      - "3080:3080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  data:
```

the s3gw-ui container does not start:
```
test-s3gw-ui-1  | The value of the environment variable S3GW_UI_PATH is malformed: /
test-s3gw-ui-1  | The value of the environment variable S3GW_UI_PATH is malformed
test-s3gw-ui-1  | Unable to init config -- exit!
test-s3gw-ui-1 exited with code 0
```
